services:
  - type: web
    name: city-fit
    runtime: static
    buildCommand: ""  # 已经构建好了
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
